# Generated by Django 3.2.5 on 2021-08-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=50, null=True, verbose_name='app名称')),
                ('name', models.CharField(default='菜单管理', max_length=50, unique=True, verbose_name='名称')),
                ('icon', models.CharField(default='fas fa-user-shield', max_length=50, verbose_name='图标')),
                ('url', models.CharField(blank=True, default='simpleuimenu/menu/', max_length=50, null=True, verbose_name='路径')),
                ('level', models.IntegerField(choices=[(1, '一级菜单'), (2, '二级菜单'), (3, '三级菜单')], default=1, verbose_name='层级')),
                ('parent', models.ForeignKey(blank=True, default=0, help_text='非一级菜单才生效', null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleuimenu.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单管理',
                'verbose_name_plural': '菜单管理',
                'db_table': 'simplemenu',
            },
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ManyToManyField(blank=True, to='simpleuimenu.Menu', verbose_name='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '授权用户',
                'verbose_name_plural': '授权用户',
                'db_table': 'simplemenu_user',
            },
        ),
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('menu', models.ManyToManyField(blank=True, to='simpleuimenu.Menu', verbose_name='')),
            ],
            options={
                'verbose_name': '授权组',
                'verbose_name_plural': '授权组',
                'db_table': 'simplemenu_group',
            },
        ),
    ]
